[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CONAn"
authors = [{name = "Leonard Dick", email = "dick@thch.uni-bonn.de}]
dynamic = ["version", "description"]
